### ISSUE TITLE
Migrate to spotify/web-scripts

### ISSUE THREAD

**Issue by ekh64** [spotify/reactochart#160] opened 2019-07-23 15:34 UTC
Spotify open sourced a whole load of configs, [spotify/web-scripts](https://github.com/spotify/web-scripts), maybe we could use them to keep our code tidy?

**Comment by arjbholu** [comment] 2019-07-23 16:57
Hi,
I would like to take up this issue. Can you please help me from where I should start?

**Comment by ekh64** [comment] 2019-07-23 17:01
I think a good starting point is to [add the `eslint` configs, along with `prettier` config](https://github.com/spotify/web-scripts#spotify-shared-configurations), rather than use the entire suite wholesale. We can always do that later on.

**Comment by krissalvador27** [comment] 2019-07-23 17:18
Hey @arjbholu! What @ekh64 said is spot on. Would require a change to our `.eslintrc.json` and adding the prettier config (right now our eslint setup just uses prettier's rules).

**Comment by krissalvador27** [comment] 2019-07-25 19:05
Hey @arjbholu, just following up to see how this is going and if you need any support on this at all? Let me know 👍

**Comment by arjbholu** [comment] 2019-07-26 06:34
@krissalvador27 I will work on it and will close within a day or two. If I will need help, I will surely let you know. Thanks for asking :)

**Comment by arjbholu** [comment] 2019-07-28 07:53
@krissalvador27 Correct me if I am wrong or do you need something more.
1. I added [this](https://github.com/spotify/web-scripts/tree/master/packages/eslint-config-react) to dev dependencies. 
2. Updated the `.eslintrc.json` with ""@spotify/eslint-config-react" instead of "plugin:prettier/recommended".

**Comment by krissalvador27** [comment] 2019-07-29 02:15
Hey @arjbholu,

Awesome to hear! Just a few things

1. We should also add the `@spotify/eslint-config-base`. Directions for that can be found [here](https://github.com/spotify/web-scripts/tree/master/packages/eslint-config-base).
2. We should then remove the `plugin:prettier/recommended` from the `.eslintrc.json`, along with the `eslint-plugin-prettier` dev dependency.
3. Then we can add Spotify's prettier config documented [here](https://github.com/spotify/web-scripts/tree/master/packages/prettier-config).
4. Lastly we can add `prettier` as the last extension in our `eslintrc.json`. The `eslint-config-prettier` dev dependency should allow us to turn off eslint rules that conflict with prettier and use Spotify's prettier config.

I think this would be a great first step, and we can consider adding the full suite, like automating the linting process with husky afterwards. What do you think @ekh64?

**Comment by arjbholu** [comment] 2019-07-29 15:17
@krissalvador27 I have made the changes but I am getting the following error while running `npm run build`

![image](https://user-images.githubusercontent.com/8599981/62060054-13b93000-b242-11e9-8467-9bb3f266cffe.png)

Can you please help me out here

**Comment by krissalvador27** [comment] 2019-07-29 15:53
@arjbholu What OS are you using? I wonder if this has to do with cross env issues.

**Comment by arjbholu** [comment] 2019-07-29 15:56
@krissalvador27 I am using windows. I will try once in linux and get back to you.
Thanks

**Comment by arjbholu** [comment] 2019-07-29 16:58
@krissalvador27 I was able to run build in linux. Just had this one doubt: after running the command, some 100 files were added on its own. Please see in the attached screenshot. Is it expected behavior? Should check in those file? Because I made changes into 3 files only.

![Screenshot from 2019-07-29 22:26:30](https://user-images.githubusercontent.com/8599981/62066953-36eadc00-b250-11e9-9657-010d88ed467f.png)

**Comment by krissalvador27** [comment] 2019-07-29 17:16
@arjbholu You can run `npm run clean` and that should remove the generated files. We don't commit the build files.

Thanks for confirming that it works in linux! Seems like it is `cross-env` issue that we need to address as soon as possible so other developers such as yourself don't run into these types of issues in the future 😅.

**Comment by arjbholu** [comment] 2019-07-31 14:05
@krissalvador27 I will work on your comments to my PR. But can we close that cross-env issue, so that I can code on windows :P

**Comment by arjbholu** [comment] 2019-08-01 16:43
@krissalvador27 let me know when you are online

would like to connect with you online.

**Comment by arjbholu** [comment] 2019-08-01 17:41
@krissalvador27 
can you please check [https://github.com/arjbholu/reactochart/commit/76392c5fafe8ad3341ba26be24b4b5eb9857b0e2](this) commit?

**Comment by krissalvador27** [comment] 2019-08-09 14:24
Hey @arjbholu, sorry for the late reply was on vacation. That commit looks right! You should be getting eslint and prettier errors that I can happily take over and push changes up to your branch. Let me know if you'd like to still sync online - happy to do so!

**Comment by arjbholu** [comment] 2019-08-09 14:52
Hey @krissalvador27 . Thanks for letting me know. You can continue with my branch. Should I make a PR?

**Comment by krissalvador27** [comment] 2019-08-12 00:56
Hey @arjbholu, yeah you could push that commit to your [existing PR](https://github.com/spotify/reactochart/pull/162) or close it and open a new one and I can work off of it from there and go through the lint errors. 😄

**Comment by krissalvador27** [comment] 2019-08-22 02:31
Resolved via #173 and will go out in version 2!

**Closed by krissalvador27** 2019-08-22 02:31 UTC
Labels: good first issue, infra
